In [21]:
input = readlines("data/19-input.txt")

30-element Vector{String}:
 "Blueprint 1: Each ore robot cos" ⋯ 98 bytes ⋯ "ot costs 4 ore and 19 obsidian."
 "Blueprint 2: Each ore robot cos" ⋯ 97 bytes ⋯ "bot costs 2 ore and 7 obsidian."
 "Blueprint 3: Each ore robot cos" ⋯ 98 bytes ⋯ "ot costs 3 ore and 12 obsidian."
 "Blueprint 4: Each ore robot cos" ⋯ 98 bytes ⋯ "ot costs 2 ore and 19 obsidian."
 "Blueprint 5: Each ore robot cos" ⋯ 98 bytes ⋯ "ot costs 4 ore and 13 obsidian."
 "Blueprint 6: Each ore robot cos" ⋯ 97 bytes ⋯ "ot costs 4 ore and 11 obsidian."
 "Blueprint 7: Each ore robot cos" ⋯ 98 bytes ⋯ "ot costs 4 ore and 17 obsidian."
 "Blueprint 8: Each ore robot cos" ⋯ 97 bytes ⋯ "bot costs 3 ore and 7 obsidian."
 "Blueprint 9: Each ore robot cos" ⋯ 98 bytes ⋯ "ot costs 3 ore and 15 obsidian."
 "Blueprint 10: Each ore robot co" ⋯ 99 bytes ⋯ "ot costs 4 ore and 11 obsidian."
 ⋮
 "Blueprint 22: Each ore robot co" ⋯ 99 bytes ⋯ "ot costs 4 ore and 16 obsidian."
 "Blueprint 23: Each ore robot co" ⋯ 99 bytes ⋯ "ot costs 4 ore and 

In [22]:
test_data = input[1]

"Blueprint 1: Each ore robot costs 4 ore. Each clay robot costs 4 ore. Each obsidian robot costs 4 ore and 12 clay. Each geode robot costs 4 ore and 19 obsidian."

In [23]:
spliti = split(test_data, " ", )

32-element Vector{SubString{String}}:
 "Blueprint"
 "1:"
 "Each"
 "ore"
 "robot"
 "costs"
 "4"
 "ore."
 "Each"
 "clay"
 ⋮
 "Each"
 "geode"
 "robot"
 "costs"
 "4"
 "ore"
 "and"
 "19"
 "obsidian."

In [24]:
spliti[[3,13]]

2-element Vector{SubString{String}}:
 "Each"
 "4"

In [25]:
for (i,x) in enumerate(spliti) 
    println(i," ",x)
end

1 Blueprint
2 1:
3 Each
4 ore
5 robot
6 costs
7 4
8 ore.
9 Each
10 clay
11 robot
12 costs
13 4
14 ore.
15 Each
16 obsidian
17 robot
18 costs
19 4
20 ore
21 and
22 12
23 clay.
24 Each
25 geode
26 robot
27 costs
28 4
29 ore
30 and
31 19
32 obsidian.


In [26]:
function get_costs(line)
    spliti = split(line," ")
    #ore-ore, ore-clay, ore-obsidian, clay-obsidian, ore-geode, obsidian-geode
    return parse.(Int,spliti[[7,13,19,22,28,31]])
end
    

get_costs (generic function with 1 method)

In [ ]:
costs = get_costs(input[1])

In [ ]:
blueprints = get_costs.(input)

In [ ]:
function solve_everything(costs)
    # ore, clay,obsidian, geode, ore_r, caly_r, obsidian_r, geode_r, time
    states = Set([[0,0,0,0,1,0,0,0]])
    #ore-ore, ore-clay, ore-obsidian, clay-obsidian, ore-geode, obsidian-geode
    for t in 1:24
        states = get_new_states(states, costs)
        println("Finished step $t at length ", length(states))
    end
    #get_max_geode(states)
    return maximum([x[4] for x in result])
end

In [ ]:
function get_new_states(states, costs)
    new_states = Set{Vector{Int}}()
    for state in states
        c = child_states(state, costs) 
        for s in c
            push!(new_states, s)
        end
    end
    return new_states
end

In [ ]:
function child_states(state::Vector{Int}, costs)
    new_resource = new_resources(state)
    children = [new_resource]
    if state[1] >= costs[1]
        push!(children, new_resource+[-costs[1], 0, 0, 0, 1, 0, 0, 0])
    end
    if state[1] >= costs[2]
        push!(children, new_resource+[-costs[2], 0, 0, 0, 0, 1, 0, 0])
    end
    if state[1] >= costs[3] && state[2] >= costs[4]
        push!(children, new_resource+[-costs[3], -costs[4], 0, 0, 0, 0, 1, 0])
    end
    if state[1] >= costs[5] && state[3] >= costs[6]
        push!(children, new_resource+[-costs[5], 0, -costs[6], 0, 0, 0, 0, 1])
    end
    return children
end

In [ ]:
function new_resources(state)
    return state.+[state[5:end]..., 0,0,0,0]
end

In [ ]:
child_states([4,4,4,4,2,2,2,2], costs)

In [ ]:
get_new_states(Set([[10,20,0,0,1,0,0,1]]), costs)

In [ ]:
result = solve_everything(costs)

In [ ]:
maximum([x[4] for x in result])

In [ ]:
vals = zeros(length(blueprints))
Threads.@threads for i in 1:length(blueprints)
        vals[i] = i*solve_everything(blueprints[i])
end

In [ ]:
sum(vals)

In [ ]:
length(costs)